name: Actions para estudar

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Isto configura a execução a cada hora

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run a script on push
        run: echo "Este job é executado quando ocorrer push na main branch"

  job_2:
    runs-on: ubuntu-latest
    needs: [job_1]
    steps:
      - name: Postar um comentário
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          COMMENT="Este é um comentário agendado que será postado a cada hora, até o dia 06/07/2024."
          ISSUE_NUMBER=1  # Número da issue que será comentado
          curl -H "Authorization: token $GH_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/adelitab/github-actions-dotnet-webapp/issues/${ISSUE_NUMBER}/comments \
               -d "{\"body\": \"$COMMENT\"}"
